FROM python:3.12-slim

# Cache buster: v3-no-postgis
ENV APP_VERSION=v3-no-postgis

WORKDIR /app

COPY requirements.api.txt .
RUN pip install --no-cache-dir -r requirements.api.txt

COPY . .

CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]
